### ISSUE TITLE
Division by 0

### ISSUE THREAD

**Issue by mercuriete** [infracost/infracost-gh-action#17]
steps to reproduce:
1. create an empty terraform project
2. add infracost-gh-actions on github actions
3. before cost is 0 and after cost is 0. 0/0% = NAN%

Tomorrow I will create an empty repository with the reproducer.

Logs:
```
 $ infracost --no-color --usage-file infracost-usage.yml
time="2021-01-27T17:12:46Z" level=info msg="starting: Running terraform init"
time="2021-01-27T17:12:46Z" level=info msg="Running command: /usr/bin/terraform init -input=false -no-color"
time="2021-01-27T17:12:52Z" level=info msg="starting: Running terraform plan"
time="2021-01-27T17:12:52Z" level=info msg="Running command: /usr/bin/terraform plan -input=false -lock=false -no-color -out=/tmp/tfplan546450212"
time="2021-01-27T17:12:53Z" level=info msg="starting: Running terraform show"
time="2021-01-27T17:12:53Z" level=info msg="Running command: /usr/bin/terraform show -no-color -json /tmp/tfplan546450212"
time="2021-01-27T17:12:54Z" level=info msg="starting: Calculating cost estimate"
bc: divide by zero
```

**Comment by alikhajeh1** [comment]
@mercuriete thanks for reporting this! No need for a reproducer repo, the repro steps were clear - will fix it.

**Comment by alikhajeh1** [comment]
@mercuriete I [added a fix](https://github.com/infracost/infracost/commit/9474f58b44a35321e9157ca9890c589a7b3729b2) in v0.7.16 of infracost (the GH Action uses the diff.sh script in the docker image).

**Comment by mercuriete** [comment]
Thanks!

Your product is awesome, keep going!
:+1:
