### ISSUE TITLE
Disable auto comment in PR

### ISSUE THREAD

**Issue by timurkhisamov** [infracost/infracost-gh-action#31]
Hello, devs. Could you please tell me how to disable auto comments in pull requests in GHA, but I still want `outputs`.

I tried the `post_condition` options with no results.

**Comment by alikhajeh1** [comment]
@timurkhisamov we don't have a way to do that, maybe you can try `post_condition='{"percentage_threshold": 9999}'` so the threshold is so high that a comment is never posted? I'm curious, can please share more context around what you're trying to do and why you don't want comments?
